name: crm-backend

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      NODE_ENV: production
      PORT: "4040"
      DATABASE_URL: "mysql://<USER>:<PASSWORD>@<LOOPIA_HOST>:3306/<DB>?sslaccept=strict"
      ALLOWED_ORIGINS: "https://your-frontend-on-loopia.example"
      ENABLE_AI: "false"
      AI_PROVIDER: "none"
      AI_API_KEY: ""
      AI_API_BASE: ""
      AI_MODEL: ""
      AI_TIMEOUT_MS: "30000"
      AI_MAX_TOKENS: "1024"
      AI_RATE_LIMIT_RPM: "60"
      ENABLE_SEARCH_PROXY: "false"
      ALLOW_SHELL_SCRIPTS: "false"
    ports:
      - "4040:4040"
    restart: unless-stopped
