# docker-compose stack for the decoupled CRM backend
# This file keeps a single service (backend) that connects to the remote Loopia MariaDB.

name: ${COMPOSE_PROJECT_NAME_PROD}

services:
  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    env_file:
      - ../backend/.env.production.backend
    environment:
      # Allow overriding from the host environment, but provide safe defaults for feature flags.
      DATABASE_URL: ${DATABASE_URL:-}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-https://your-loopia-frontend.example}
      ENABLE_AI: ${ENABLE_AI:-false}
      ENABLE_SEARCH_PROXY: ${ENABLE_SEARCH_PROXY:-false}
      ALLOW_SHELL_SCRIPTS: ${ALLOW_SHELL_SCRIPTS:-false}
    ports:
      - "${BACKEND_PORT_PROD:-4040}:4040"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4040/api/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
