# Development docker-compose stack for the standalone CRM backend

name: ${COMPOSE_PROJECT_NAME_DEV}

services:
  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    env_file:
      - ../backend/.env.production.backend
    environment:
      DATABASE_URL: ${DATABASE_URL:-}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-http://localhost:3000}
      ENABLE_AI: ${ENABLE_AI:-false}
      ENABLE_SEARCH_PROXY: ${ENABLE_SEARCH_PROXY:-false}
      ALLOW_SHELL_SCRIPTS: ${ALLOW_SHELL_SCRIPTS:-false}
    ports:
      - "${BACKEND_PORT_DEV:-4040}:4040"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4040/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
