# Docker-compose för DEVELOPMENT miljö
# Använder volume mounts för hot reload

name: crm-members-dev
networks:
  crm-network:
    driver: bridge

services:
  # =========================
  # MySQL Database
  # =========================
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_change_me
      MYSQL_DATABASE: crm_db
      MYSQL_USER: crm_user
      MYSQL_PASSWORD: crm_password
      TZ: "Europe/Stockholm"
    volumes:
      - ./storage/dev/mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT:-3326}:3306"
    networks:
      - crm-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  # =========================
  # phpMyAdmin
  # =========================
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: crm_user
      PMA_PASSWORD: crm_password
      UPLOAD_LIMIT: 100M
      TZ: "Europe/Stockholm"
    ports:
      - "${PHPMYADMIN_PORT:-8270}:80"
    networks:
      - crm-network
    depends_on:
      mysql:
        condition: service_healthy

  # =========================
  # Redis (för caching)
  # =========================
  redis:
    image: redis:7-alpine
    restart: always
    command: redis-server --appendonly yes --requirepass redis_dev
    volumes:
      - ./storage/dev/redis:/data
    ports:
      - "${REDIS_PORT:-6279}:6379"
    networks:
      - crm-network
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "redis_dev", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # =========================
  # Next.js Application (DEV)
  # =========================
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      # Database
      DATABASE_URL: "mysql://crm_user:crm_password_change_me@mysql:3306/crm_db"
      
      # Redis
      REDIS_URL: "redis://:redis_dev@redis:6379"
      
      # App
      NODE_ENV: "development"
      NEXT_PUBLIC_APP_URL: "http://localhost:3020
      
      # NextAuth
      NEXTAUTH_URL: "http://localhost:3020
      NEXTAUTH_SECRET: "dev_secret_change_in_production"
    
    # AI Providers (valfritt)
    # OPENAI_API_KEY: "your-key-here"
    # ANTHROPIC_API_KEY: "your-key-here"
    # OLLAMA_HOST: "http://host.docker.internal:11434"
    
      TZ: "Europe/Stockholm"
    volumes:
      # Volume mounts för hot reload
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "${APP_PORT:-3020}:3000"
    networks:
      - crm-network
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    # Development server med hot reload
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"
volumes:
  mysql_data:
  redis_data:
